### ISSUE TITLE
Consolidate all YNAB converter scripts into just one?

### ISSUE THREAD

**Issue by torbengb** [adnilsson/Bank2YNAB#1]
Hejsan Adrian!
I've noticed that there are more than 80 GitHub projects related to YNAB converter scripts. Would it be helpful and would there be interest in an effort to consolidate all (most) of these into a single tool? On the plus side, clearly there's more than enough solutions and contributors. On the minus side, these are spread across different spoken languages, programming languages, and of course bank export formats.

You're probably familiar with the YNAB subreddit. I've posted this idea here for a joint discussion: https://www.reddit.com/r/ynab/comments/75fctx/tools_can_we_consolidate_all_our_ynab_import/

Hälsningar från Wien,
Ben

**Comment by adnilsson** [comment]
I'm not at all opposed to the idea, and you seem to already have come quite some way in developing a common ground. However, note that I'm using the old YNAB 4, and I have no intention of switching to their new platform. I may therefore not be able to contribute much to the development of a conversion tool targeted at YNAB 5+, though I will fill out your spreadsheet with my bank's csv format.

**Comment by torbengb** [comment]
Thanks for the response :) I believe the YNAB import CSV format is identical so our script should be universal. Of course, since you've already built the conversion that you need, you're not directly affected either way. 
Best regards,
Ben

**Comment by adnilsson** [comment]
It's true that the CSV format is identical, but my thought was that the newer platform might do some more intelligent parsing of the CSV file to support e.g. a wider range of different date formats. For instance YNAB 4 does not accept the swedish date format yyyy-mm-dd, I had to parse that column.

**Comment by torbengb** [comment]
We are preparing a plugin system for our script that is useful for such
cases when the data needs to be manipulated, rather than just reordered. If
you don't mind, I'd like to take your case as a reason to build a sample
plugin. This plugin stuff isn't documented yet though (that's another issue
:-) ) so I can't pass you a specific link about it yet.
